/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITAntChannelIdMesg : FITMessage
- (id)init;
// ChannelNumber 
- (BOOL)isChannelNumberValid;
- (FITUInt8)getChannelNumber;
- (void)setChannelNumber:(FITUInt8)channelNumber;
// DeviceType 
- (BOOL)isDeviceTypeValid;
- (FITUInt8z)getDeviceType;
- (void)setDeviceType:(FITUInt8z)deviceType;
// DeviceNumber 
- (BOOL)isDeviceNumberValid;
- (FITUInt16z)getDeviceNumber;
- (void)setDeviceNumber:(FITUInt16z)deviceNumber;
// TransmissionType 
- (BOOL)isTransmissionTypeValid;
- (FITUInt8z)getTransmissionType;
- (void)setTransmissionType:(FITUInt8z)transmissionType;
// DeviceIndex 
- (BOOL)isDeviceIndexValid;
- (FITDeviceIndex)getDeviceIndex;
- (void)setDeviceIndex:(FITDeviceIndex)deviceIndex;

@end

NS_ASSUME_NONNULL_END
