/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2022 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.94Release
// Tag = production/akw/21.94.00-0-g0f668193
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITTypes.h"
#import "FITFieldDescriptionMesg.h"
#import "FITDeveloperDataIdMesg.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITDeveloperField : NSObject

- (id)initWithFieldDescriptionMesg: (FITFieldDescriptionMesg*) definition andDeveloperDataIdMesg: (FITDeveloperDataIdMesg*) developer;
- (void)addValue:(NSNumber*)value forIndex:(uint8_t)index;
- (NSNumber*)getValueForIndex:(uint8_t)index;

@property(nonatomic, readonly) FITFieldDescriptionMesg* definition;
@property(nonatomic, readonly) FITDeveloperDataIdMesg* developer;

@end

NS_ASSUME_NONNULL_END