/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITMessage.h"

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, FITProtocolVersion) {
    FITProtocolVersionV10,
    FITProtocolVersionV20
};

@interface FITEncoder : NSObject

- (instancetype)initWithVersion:(FITProtocolVersion)version NS_DESIGNATED_INITIALIZER;
- (instancetype)init NS_UNAVAILABLE;

- (BOOL)open:(NSString *)filename;
- (void)writeMessage:(FITMessage *)mesg;
- (void)writeMessages:(NSArray<FITMessage *>*)mesgs;
- (BOOL)close;

@end

NS_ASSUME_NONNULL_END
