/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITExerciseTitleMesg : FITMessage
- (id)init;
// MessageIndex 
- (BOOL)isMessageIndexValid;
- (FITMessageIndex)getMessageIndex;
- (void)setMessageIndex:(FITMessageIndex)messageIndex;
// ExerciseCategory 
- (BOOL)isExerciseCategoryValid;
- (FITExerciseCategory)getExerciseCategory;
- (void)setExerciseCategory:(FITExerciseCategory)exerciseCategory;
// ExerciseName 
- (BOOL)isExerciseNameValid;
- (FITUInt16)getExerciseName;
- (void)setExerciseName:(FITUInt16)exerciseName;
// WktStepName 
@property(readonly,nonatomic) uint8_t numWktStepNameValues;
- (BOOL)isWktStepNameValidforIndex : (uint8_t)index;
- (NSString *)getWktStepNameforIndex : (uint8_t)index;
- (void)setWktStepName:(NSString *)wktStepName forIndex:(uint8_t)index;

@end

NS_ASSUME_NONNULL_END
