/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITDate.h"
#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITGoalMesg : FITMessage
- (id)init;
// MessageIndex 
- (BOOL)isMessageIndexValid;
- (FITMessageIndex)getMessageIndex;
- (void)setMessageIndex:(FITMessageIndex)messageIndex;
// Sport 
- (BOOL)isSportValid;
- (FITSport)getSport;
- (void)setSport:(FITSport)sport;
// SubSport 
- (BOOL)isSubSportValid;
- (FITSubSport)getSubSport;
- (void)setSubSport:(FITSubSport)subSport;
// StartDate 
- (BOOL)isStartDateValid;
- (FITDate *)getStartDate;
- (void)setStartDate:(FITDate *)startDate;
// EndDate 
- (BOOL)isEndDateValid;
- (FITDate *)getEndDate;
- (void)setEndDate:(FITDate *)endDate;
// Type 
- (BOOL)isTypeValid;
- (FITGoal)getType;
- (void)setType:(FITGoal)type;
// Value 
- (BOOL)isValueValid;
- (FITUInt32)getValue;
- (void)setValue:(FITUInt32)value;
// Repeat 
- (BOOL)isRepeatValid;
- (FITBool)getRepeat;
- (void)setRepeat:(FITBool)repeat;
// TargetValue 
- (BOOL)isTargetValueValid;
- (FITUInt32)getTargetValue;
- (void)setTargetValue:(FITUInt32)targetValue;
// Recurrence 
- (BOOL)isRecurrenceValid;
- (FITGoalRecurrence)getRecurrence;
- (void)setRecurrence:(FITGoalRecurrence)recurrence;
// RecurrenceValue 
- (BOOL)isRecurrenceValueValid;
- (FITUInt16)getRecurrenceValue;
- (void)setRecurrenceValue:(FITUInt16)recurrenceValue;
// Enabled 
- (BOOL)isEnabledValid;
- (FITBool)getEnabled;
- (void)setEnabled:(FITBool)enabled;
// Source 
- (BOOL)isSourceValid;
- (FITGoalSource)getSource;
- (void)setSource:(FITGoalSource)source;

@end

NS_ASSUME_NONNULL_END
