/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITDate.h"
#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITHsaGyroscopeDataMesg : FITMessage
- (id)init;
// Timestamp 
- (BOOL)isTimestampValid;
- (FITDate *)getTimestamp;
- (void)setTimestamp:(FITDate *)timestamp;
// TimestampMs 
- (BOOL)isTimestampMsValid;
- (FITUInt16)getTimestampMs;
- (void)setTimestampMs:(FITUInt16)timestampMs;
// SamplingInterval 
- (BOOL)isSamplingIntervalValid;
- (FITUInt16)getSamplingInterval;
- (void)setSamplingInterval:(FITUInt16)samplingInterval;
// GyroX 
@property(readonly,nonatomic) uint8_t numGyroXValues;
- (BOOL)isGyroXValidforIndex : (uint8_t)index;
- (FITFloat32)getGyroXforIndex : (uint8_t)index;
- (void)setGyroX:(FITFloat32)gyroX forIndex:(uint8_t)index;
// GyroY 
@property(readonly,nonatomic) uint8_t numGyroYValues;
- (BOOL)isGyroYValidforIndex : (uint8_t)index;
- (FITFloat32)getGyroYforIndex : (uint8_t)index;
- (void)setGyroY:(FITFloat32)gyroY forIndex:(uint8_t)index;
// GyroZ 
@property(readonly,nonatomic) uint8_t numGyroZValues;
- (BOOL)isGyroZValidforIndex : (uint8_t)index;
- (FITFloat32)getGyroZforIndex : (uint8_t)index;
- (void)setGyroZ:(FITFloat32)gyroZ forIndex:(uint8_t)index;
// Timestamp32k 
- (BOOL)isTimestamp32kValid;
- (FITUInt32)getTimestamp32k;
- (void)setTimestamp32k:(FITUInt32)timestamp32k;

@end

NS_ASSUME_NONNULL_END
