/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITDate.h"
#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITHsaRespirationDataMesg : FITMessage
- (id)init;
// Timestamp 
- (BOOL)isTimestampValid;
- (FITDate *)getTimestamp;
- (void)setTimestamp:(FITDate *)timestamp;
// ProcessingInterval 
- (BOOL)isProcessingIntervalValid;
- (FITUInt16)getProcessingInterval;
- (void)setProcessingInterval:(FITUInt16)processingInterval;
// RespirationRate 
@property(readonly,nonatomic) uint8_t numRespirationRateValues;
- (BOOL)isRespirationRateValidforIndex : (uint8_t)index;
- (FITFloat32)getRespirationRateforIndex : (uint8_t)index;
- (void)setRespirationRate:(FITFloat32)respirationRate forIndex:(uint8_t)index;

@end

NS_ASSUME_NONNULL_END
