/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.115Release
// Tag = production/release/21.115.00-0-gfe0a7f8
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITHrvMesg : FITMessage
- (id)init;
// Time 
@property(readonly,nonatomic) uint8_t numTimeValues;
- (BOOL)isTimeValidforIndex : (uint8_t)index;
- (FITFloat32)getTimeforIndex : (uint8_t)index;
- (void)setTime:(FITFloat32)time forIndex:(uint8_t)index;

@end

NS_ASSUME_NONNULL_END
