/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITMemoGlobMesg : FITMessage
- (id)init;
// PartIndex 
- (BOOL)isPartIndexValid;
- (FITUInt32)getPartIndex;
- (void)setPartIndex:(FITUInt32)partIndex;
// Memo 
@property(readonly,nonatomic) uint8_t numMemoValues;
- (BOOL)isMemoValidforIndex : (uint8_t)index;
- (FITByte)getMemoforIndex : (uint8_t)index;
- (void)setMemo:(FITByte)memo forIndex:(uint8_t)index;
// MesgNum 
- (BOOL)isMesgNumValid;
- (FITMesgNum)getMesgNum;
- (void)setMesgNum:(FITMesgNum)mesgNum;
// ParentIndex 
- (BOOL)isParentIndexValid;
- (FITMessageIndex)getParentIndex;
- (void)setParentIndex:(FITMessageIndex)parentIndex;
// FieldNum 
- (BOOL)isFieldNumValid;
- (FITUInt8)getFieldNum;
- (void)setFieldNum:(FITUInt8)fieldNum;
// Data 
@property(readonly,nonatomic) uint8_t numDataValues;
- (BOOL)isDataValidforIndex : (uint8_t)index;
- (FITUInt8z)getDataforIndex : (uint8_t)index;
- (void)setData:(FITUInt8z)data forIndex:(uint8_t)index;

@end

NS_ASSUME_NONNULL_END
