/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITMetZoneMesg : FITMessage
- (id)init;
// MessageIndex 
- (BOOL)isMessageIndexValid;
- (FITMessageIndex)getMessageIndex;
- (void)setMessageIndex:(FITMessageIndex)messageIndex;
// HighBpm 
- (BOOL)isHighBpmValid;
- (FITUInt8)getHighBpm;
- (void)setHighBpm:(FITUInt8)highBpm;
// Calories 
- (BOOL)isCaloriesValid;
- (FITFloat32)getCalories;
- (void)setCalories:(FITFloat32)calories;
// FatCalories 
- (BOOL)isFatCaloriesValid;
- (FITFloat32)getFatCalories;
- (void)setFatCalories:(FITFloat32)fatCalories;

@end

NS_ASSUME_NONNULL_END
