/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITDate.h"
#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITSplitSummaryMesg : FITMessage
- (id)init;
// MessageIndex 
- (BOOL)isMessageIndexValid;
- (FITMessageIndex)getMessageIndex;
- (void)setMessageIndex:(FITMessageIndex)messageIndex;
// Timestamp 
- (BOOL)isTimestampValid;
- (FITDate *)getTimestamp;
- (void)setTimestamp:(FITDate *)timestamp;
// SplitType 
- (BOOL)isSplitTypeValid;
- (FITSplitType)getSplitType;
- (void)setSplitType:(FITSplitType)splitType;
// Sport 
- (BOOL)isSportValid;
- (FITSport)getSport;
- (void)setSport:(FITSport)sport;
// SubSport 
- (BOOL)isSubSportValid;
- (FITSubSport)getSubSport;
- (void)setSubSport:(FITSubSport)subSport;
// NumSplits 
- (BOOL)isNumSplitsValid;
- (FITUInt16)getNumSplits;
- (void)setNumSplits:(FITUInt16)numSplits;
// TotalTimerTime 
- (BOOL)isTotalTimerTimeValid;
- (FITFloat32)getTotalTimerTime;
- (void)setTotalTimerTime:(FITFloat32)totalTimerTime;
// TotalDistance 
- (BOOL)isTotalDistanceValid;
- (FITFloat32)getTotalDistance;
- (void)setTotalDistance:(FITFloat32)totalDistance;
// AvgSpeed 
- (BOOL)isAvgSpeedValid;
- (FITFloat32)getAvgSpeed;
- (void)setAvgSpeed:(FITFloat32)avgSpeed;
// MaxSpeed 
- (BOOL)isMaxSpeedValid;
- (FITFloat32)getMaxSpeed;
- (void)setMaxSpeed:(FITFloat32)maxSpeed;
// TotalAscent 
- (BOOL)isTotalAscentValid;
- (FITUInt16)getTotalAscent;
- (void)setTotalAscent:(FITUInt16)totalAscent;
// TotalDescent 
- (BOOL)isTotalDescentValid;
- (FITUInt16)getTotalDescent;
- (void)setTotalDescent:(FITUInt16)totalDescent;
// AvgHeartRate 
- (BOOL)isAvgHeartRateValid;
- (FITUInt8)getAvgHeartRate;
- (void)setAvgHeartRate:(FITUInt8)avgHeartRate;
// MaxHeartRate 
- (BOOL)isMaxHeartRateValid;
- (FITUInt8)getMaxHeartRate;
- (void)setMaxHeartRate:(FITUInt8)maxHeartRate;
// AvgVertSpeed 
- (BOOL)isAvgVertSpeedValid;
- (FITFloat32)getAvgVertSpeed;
- (void)setAvgVertSpeed:(FITFloat32)avgVertSpeed;
// TotalCalories 
- (BOOL)isTotalCaloriesValid;
- (FITUInt32)getTotalCalories;
- (void)setTotalCalories:(FITUInt32)totalCalories;
// AvgCadence 
- (BOOL)isAvgCadenceValid;
- (FITFloat32)getAvgCadence;
- (void)setAvgCadence:(FITFloat32)avgCadence;
// AvgCadence Sub Fields
- (BOOL)isAvgRunningCadenceValid;
- (FITFloat32) getAvgRunningCadence;
- (void)setAvgRunningCadence:(FITFloat32)avgRunningCadence;
- (BOOL)isAvgSwimmingCadenceValid;
- (FITFloat32) getAvgSwimmingCadence;
- (void)setAvgSwimmingCadence:(FITFloat32)avgSwimmingCadence;
- (BOOL)isAvgPaddlesportCadenceValid;
- (FITFloat32) getAvgPaddlesportCadence;
- (void)setAvgPaddlesportCadence:(FITFloat32)avgPaddlesportCadence;
- (BOOL)isAvgPushCadenceValid;
- (FITUInt16) getAvgPushCadence;
- (void)setAvgPushCadence:(FITUInt16)avgPushCadence;
// MaxCadence 
- (BOOL)isMaxCadenceValid;
- (FITFloat32)getMaxCadence;
- (void)setMaxCadence:(FITFloat32)maxCadence;
// MaxCadence Sub Fields
- (BOOL)isMaxRunningCadenceValid;
- (FITFloat32) getMaxRunningCadence;
- (void)setMaxRunningCadence:(FITFloat32)maxRunningCadence;
- (BOOL)isMaxSwimmingCadenceValid;
- (FITFloat32) getMaxSwimmingCadence;
- (void)setMaxSwimmingCadence:(FITFloat32)maxSwimmingCadence;
- (BOOL)isMaxPaddlesportCadenceValid;
- (FITFloat32) getMaxPaddlesportCadence;
- (void)setMaxPaddlesportCadence:(FITFloat32)maxPaddlesportCadence;
- (BOOL)isMaxPushCadenceValid;
- (FITUInt16) getMaxPushCadence;
- (void)setMaxPushCadence:(FITUInt16)maxPushCadence;
// TotalCycles 
- (BOOL)isTotalCyclesValid;
- (FITUInt32)getTotalCycles;
- (void)setTotalCycles:(FITUInt32)totalCycles;
// TotalCycles Sub Fields
- (BOOL)isTotalStridesValid;
- (FITUInt32) getTotalStrides;
- (void)setTotalStrides:(FITUInt32)totalStrides;
- (BOOL)isTotalStrokesValid;
- (FITUInt32) getTotalStrokes;
- (void)setTotalStrokes:(FITUInt32)totalStrokes;
- (BOOL)isTotalRepsValid;
- (FITUInt32) getTotalReps;
- (void)setTotalReps:(FITUInt32)totalReps;
- (BOOL)isTotalPushesValid;
- (FITUInt32) getTotalPushes;
- (void)setTotalPushes:(FITUInt32)totalPushes;
// AvgTemperature 
- (BOOL)isAvgTemperatureValid;
- (FITSInt8)getAvgTemperature;
- (void)setAvgTemperature:(FITSInt8)avgTemperature;
// MaxTemperature 
- (BOOL)isMaxTemperatureValid;
- (FITSInt8)getMaxTemperature;
- (void)setMaxTemperature:(FITSInt8)maxTemperature;
// MinTemperature 
- (BOOL)isMinTemperatureValid;
- (FITSInt8)getMinTemperature;
- (void)setMinTemperature:(FITSInt8)minTemperature;
// AvgVerticalOscillation 
- (BOOL)isAvgVerticalOscillationValid;
- (FITFloat32)getAvgVerticalOscillation;
- (void)setAvgVerticalOscillation:(FITFloat32)avgVerticalOscillation;
// AvgVerticalRatio 
- (BOOL)isAvgVerticalRatioValid;
- (FITFloat32)getAvgVerticalRatio;
- (void)setAvgVerticalRatio:(FITFloat32)avgVerticalRatio;
// AvgStanceTime 
- (BOOL)isAvgStanceTimeValid;
- (FITFloat32)getAvgStanceTime;
- (void)setAvgStanceTime:(FITFloat32)avgStanceTime;
// AvgStanceTimeBalance 
- (BOOL)isAvgStanceTimeBalanceValid;
- (FITFloat32)getAvgStanceTimeBalance;
- (void)setAvgStanceTimeBalance:(FITFloat32)avgStanceTimeBalance;
// AvgStepLength 
- (BOOL)isAvgStepLengthValid;
- (FITFloat32)getAvgStepLength;
- (void)setAvgStepLength:(FITFloat32)avgStepLength;
// AvgPower 
- (BOOL)isAvgPowerValid;
- (FITUInt16)getAvgPower;
- (void)setAvgPower:(FITUInt16)avgPower;
// MaxPower 
- (BOOL)isMaxPowerValid;
- (FITUInt16)getMaxPower;
- (void)setMaxPower:(FITUInt16)maxPower;
// NormalizedPower 
- (BOOL)isNormalizedPowerValid;
- (FITUInt16)getNormalizedPower;
- (void)setNormalizedPower:(FITUInt16)normalizedPower;
// LeftRightBalance 
- (BOOL)isLeftRightBalanceValid;
- (FITLeftRightBalance100)getLeftRightBalance;
- (void)setLeftRightBalance:(FITLeftRightBalance100)leftRightBalance;
// TimeStanding 
- (BOOL)isTimeStandingValid;
- (FITFloat32)getTimeStanding;
- (void)setTimeStanding:(FITFloat32)timeStanding;
// AvgLeftPco 
- (BOOL)isAvgLeftPcoValid;
- (FITSInt8)getAvgLeftPco;
- (void)setAvgLeftPco:(FITSInt8)avgLeftPco;
// AvgRightPco 
- (BOOL)isAvgRightPcoValid;
- (FITSInt8)getAvgRightPco;
- (void)setAvgRightPco:(FITSInt8)avgRightPco;
// AvgLeftPowerPhase 
@property(readonly,nonatomic) uint8_t numAvgLeftPowerPhaseValues;
- (BOOL)isAvgLeftPowerPhaseValidforIndex : (uint8_t)index;
- (FITFloat32)getAvgLeftPowerPhaseforIndex : (uint8_t)index;
- (void)setAvgLeftPowerPhase:(FITFloat32)avgLeftPowerPhase forIndex:(uint8_t)index;
// AvgLeftPowerPhasePeak 
@property(readonly,nonatomic) uint8_t numAvgLeftPowerPhasePeakValues;
- (BOOL)isAvgLeftPowerPhasePeakValidforIndex : (uint8_t)index;
- (FITFloat32)getAvgLeftPowerPhasePeakforIndex : (uint8_t)index;
- (void)setAvgLeftPowerPhasePeak:(FITFloat32)avgLeftPowerPhasePeak forIndex:(uint8_t)index;
// AvgRightPowerPhase 
@property(readonly,nonatomic) uint8_t numAvgRightPowerPhaseValues;
- (BOOL)isAvgRightPowerPhaseValidforIndex : (uint8_t)index;
- (FITFloat32)getAvgRightPowerPhaseforIndex : (uint8_t)index;
- (void)setAvgRightPowerPhase:(FITFloat32)avgRightPowerPhase forIndex:(uint8_t)index;
// AvgRightPowerPhasePeak 
@property(readonly,nonatomic) uint8_t numAvgRightPowerPhasePeakValues;
- (BOOL)isAvgRightPowerPhasePeakValidforIndex : (uint8_t)index;
- (FITFloat32)getAvgRightPowerPhasePeakforIndex : (uint8_t)index;
- (void)setAvgRightPowerPhasePeak:(FITFloat32)avgRightPowerPhasePeak forIndex:(uint8_t)index;
// AvgPowerPosition 
@property(readonly,nonatomic) uint8_t numAvgPowerPositionValues;
- (BOOL)isAvgPowerPositionValidforIndex : (uint8_t)index;
- (FITUInt16)getAvgPowerPositionforIndex : (uint8_t)index;
- (void)setAvgPowerPosition:(FITUInt16)avgPowerPosition forIndex:(uint8_t)index;
// MaxPowerPosition 
@property(readonly,nonatomic) uint8_t numMaxPowerPositionValues;
- (BOOL)isMaxPowerPositionValidforIndex : (uint8_t)index;
- (FITUInt16)getMaxPowerPositionforIndex : (uint8_t)index;
- (void)setMaxPowerPosition:(FITUInt16)maxPowerPosition forIndex:(uint8_t)index;
// AvgLeftTorqueEffectiveness 
- (BOOL)isAvgLeftTorqueEffectivenessValid;
- (FITFloat32)getAvgLeftTorqueEffectiveness;
- (void)setAvgLeftTorqueEffectiveness:(FITFloat32)avgLeftTorqueEffectiveness;
// AvgRightTorqueEffectiveness 
- (BOOL)isAvgRightTorqueEffectivenessValid;
- (FITFloat32)getAvgRightTorqueEffectiveness;
- (void)setAvgRightTorqueEffectiveness:(FITFloat32)avgRightTorqueEffectiveness;
// AvgLeftPedalSmoothness 
- (BOOL)isAvgLeftPedalSmoothnessValid;
- (FITFloat32)getAvgLeftPedalSmoothness;
- (void)setAvgLeftPedalSmoothness:(FITFloat32)avgLeftPedalSmoothness;
// AvgRightPedalSmoothness 
- (BOOL)isAvgRightPedalSmoothnessValid;
- (FITFloat32)getAvgRightPedalSmoothness;
- (void)setAvgRightPedalSmoothness:(FITFloat32)avgRightPedalSmoothness;
// AvgCombinedPedalSmoothness 
- (BOOL)isAvgCombinedPedalSmoothnessValid;
- (FITFloat32)getAvgCombinedPedalSmoothness;
- (void)setAvgCombinedPedalSmoothness:(FITFloat32)avgCombinedPedalSmoothness;
// AvgFlow 
- (BOOL)isAvgFlowValid;
- (FITFloat32)getAvgFlow;
- (void)setAvgFlow:(FITFloat32)avgFlow;
// TotalGrit 
- (BOOL)isTotalGritValid;
- (FITFloat32)getTotalGrit;
- (void)setTotalGrit:(FITFloat32)totalGrit;
// SwimStroke 
- (BOOL)isSwimStrokeValid;
- (FITSwimStroke)getSwimStroke;
- (void)setSwimStroke:(FITSwimStroke)swimStroke;
// NumActiveLengths 
- (BOOL)isNumActiveLengthsValid;
- (FITUInt16)getNumActiveLengths;
- (void)setNumActiveLengths:(FITUInt16)numActiveLengths;
// AvgSwolf 
- (BOOL)isAvgSwolfValid;
- (FITUInt16)getAvgSwolf;
- (void)setAvgSwolf:(FITUInt16)avgSwolf;
// AvgStrokeDistance 
- (BOOL)isAvgStrokeDistanceValid;
- (FITFloat32)getAvgStrokeDistance;
- (void)setAvgStrokeDistance:(FITFloat32)avgStrokeDistance;
// AvgStrokesPerLength 
- (BOOL)isAvgStrokesPerLengthValid;
- (FITFloat32)getAvgStrokesPerLength;
- (void)setAvgStrokesPerLength:(FITFloat32)avgStrokesPerLength;
// AvgAscent 
- (BOOL)isAvgAscentValid;
- (FITUInt16)getAvgAscent;
- (void)setAvgAscent:(FITUInt16)avgAscent;
// MaxAscent 
- (BOOL)isMaxAscentValid;
- (FITUInt16)getMaxAscent;
- (void)setMaxAscent:(FITUInt16)maxAscent;
// ClimbGradingScale 
- (BOOL)isClimbGradingScaleValid;
- (FITClimbGradingScale)getClimbGradingScale;
- (void)setClimbGradingScale:(FITClimbGradingScale)climbGradingScale;
// ClimbMaxGradeValue 
- (BOOL)isClimbMaxGradeValueValid;
- (FITUInt32)getClimbMaxGradeValue;
- (void)setClimbMaxGradeValue:(FITUInt32)climbMaxGradeValue;
// ClimbMaxGradeValue Sub Fields
- (BOOL)isClimbMaxGradeYdsValid;
- (FITYdsGradingScale) getClimbMaxGradeYds;
- (void)setClimbMaxGradeYds:(FITYdsGradingScale)climbMaxGradeYds;
- (BOOL)isClimbMaxGradeUiaaValid;
- (FITUiaaGradingScale) getClimbMaxGradeUiaa;
- (void)setClimbMaxGradeUiaa:(FITUiaaGradingScale)climbMaxGradeUiaa;
- (BOOL)isClimbMaxGradeFrenchValid;
- (FITFrenchGradingScale) getClimbMaxGradeFrench;
- (void)setClimbMaxGradeFrench:(FITFrenchGradingScale)climbMaxGradeFrench;
- (BOOL)isClimbMaxGradeBritishAdjectivalValid;
- (FITBritishAdjectivalGradingScale) getClimbMaxGradeBritishAdjectival;
- (void)setClimbMaxGradeBritishAdjectival:(FITBritishAdjectivalGradingScale)climbMaxGradeBritishAdjectival;
- (BOOL)isClimbMaxGradeBritishTechnicalValid;
- (FITBritishTechnicalGradingScale) getClimbMaxGradeBritishTechnical;
- (void)setClimbMaxGradeBritishTechnical:(FITBritishTechnicalGradingScale)climbMaxGradeBritishTechnical;
- (BOOL)isClimbMaxGradeEwbankValid;
- (FITEwbankGradingScale) getClimbMaxGradeEwbank;
- (void)setClimbMaxGradeEwbank:(FITEwbankGradingScale)climbMaxGradeEwbank;
- (BOOL)isClimbMaxGradeBrazilianValid;
- (FITBrazilianGradingScale) getClimbMaxGradeBrazilian;
- (void)setClimbMaxGradeBrazilian:(FITBrazilianGradingScale)climbMaxGradeBrazilian;
- (BOOL)isClimbMaxGradeSaxonValid;
- (FITSaxonGradingScale) getClimbMaxGradeSaxon;
- (void)setClimbMaxGradeSaxon:(FITSaxonGradingScale)climbMaxGradeSaxon;
- (BOOL)isClimbMaxGradeVerminValid;
- (FITVerminGradingScale) getClimbMaxGradeVermin;
- (void)setClimbMaxGradeVermin:(FITVerminGradingScale)climbMaxGradeVermin;
- (BOOL)isClimbMaxGradeFontValid;
- (FITFontGradingScale) getClimbMaxGradeFont;
- (void)setClimbMaxGradeFont:(FITFontGradingScale)climbMaxGradeFont;
- (BOOL)isClimbMaxGradeDankyuValid;
- (FITDankyuGradingScale) getClimbMaxGradeDankyu;
- (void)setClimbMaxGradeDankyu:(FITDankyuGradingScale)climbMaxGradeDankyu;
// NumFalls 
- (BOOL)isNumFallsValid;
- (FITUInt16)getNumFalls;
- (void)setNumFalls:(FITUInt16)numFalls;
// NumClimbsAttempted 
- (BOOL)isNumClimbsAttemptedValid;
- (FITUInt16)getNumClimbsAttempted;
- (void)setNumClimbsAttempted:(FITUInt16)numClimbsAttempted;
// NumClimbsCompleted 
- (BOOL)isNumClimbsCompletedValid;
- (FITUInt16)getNumClimbsCompleted;
- (void)setNumClimbsCompleted:(FITUInt16)numClimbsCompleted;
// MaxDistance 
- (BOOL)isMaxDistanceValid;
- (FITFloat32)getMaxDistance;
- (void)setMaxDistance:(FITFloat32)maxDistance;
// MetabolicCalories 
- (BOOL)isMetabolicCaloriesValid;
- (FITUInt16)getMetabolicCalories;
- (void)setMetabolicCalories:(FITUInt16)metabolicCalories;
// ActiveTime 
- (BOOL)isActiveTimeValid;
- (FITFloat32)getActiveTime;
- (void)setActiveTime:(FITFloat32)activeTime;
// TotalFractionalAscent 
- (BOOL)isTotalFractionalAscentValid;
- (FITFloat32)getTotalFractionalAscent;
- (void)setTotalFractionalAscent:(FITFloat32)totalFractionalAscent;
// TotalFractionalDescent 
- (BOOL)isTotalFractionalDescentValid;
- (FITFloat32)getTotalFractionalDescent;
- (void)setTotalFractionalDescent:(FITFloat32)totalFractionalDescent;
// AvgFractionalAscent 
- (BOOL)isAvgFractionalAscentValid;
- (FITFloat32)getAvgFractionalAscent;
- (void)setAvgFractionalAscent:(FITFloat32)avgFractionalAscent;
// MaxFractionalAscent 
- (BOOL)isMaxFractionalAscentValid;
- (FITFloat32)getMaxFractionalAscent;
- (void)setMaxFractionalAscent:(FITFloat32)maxFractionalAscent;
// AvgGradeAdjustedSpeed 
- (BOOL)isAvgGradeAdjustedSpeedValid;
- (FITFloat32)getAvgGradeAdjustedSpeed;
- (void)setAvgGradeAdjustedSpeed:(FITFloat32)avgGradeAdjustedSpeed;
// AvgStress 
- (BOOL)isAvgStressValid;
- (FITUInt16)getAvgStress;
- (void)setAvgStress:(FITUInt16)avgStress;
// TotalMovingTime 
- (BOOL)isTotalMovingTimeValid;
- (FITFloat32)getTotalMovingTime;
- (void)setTotalMovingTime:(FITFloat32)totalMovingTime;
// StartTime 
- (BOOL)isStartTimeValid;
- (FITDate *)getStartTime;
- (void)setStartTime:(FITDate *)startTime;
// MinHeartRate 
- (BOOL)isMinHeartRateValid;
- (FITUInt8)getMinHeartRate;
- (void)setMinHeartRate:(FITUInt8)minHeartRate;
// AvgStanceTimePercent 
- (BOOL)isAvgStanceTimePercentValid;
- (FITFloat32)getAvgStanceTimePercent;
- (void)setAvgStanceTimePercent:(FITFloat32)avgStanceTimePercent;
// MaxTotalTimerTime 
- (BOOL)isMaxTotalTimerTimeValid;
- (FITFloat32)getMaxTotalTimerTime;
- (void)setMaxTotalTimerTime:(FITFloat32)maxTotalTimerTime;

@end

NS_ASSUME_NONNULL_END
