/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITDate.h"
#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITSplitMesg : FITMessage
- (id)init;
// MessageIndex 
- (BOOL)isMessageIndexValid;
- (FITMessageIndex)getMessageIndex;
- (void)setMessageIndex:(FITMessageIndex)messageIndex;
// SplitType 
- (BOOL)isSplitTypeValid;
- (FITSplitType)getSplitType;
- (void)setSplitType:(FITSplitType)splitType;
// TotalElapsedTime 
- (BOOL)isTotalElapsedTimeValid;
- (FITFloat32)getTotalElapsedTime;
- (void)setTotalElapsedTime:(FITFloat32)totalElapsedTime;
// TotalTimerTime 
- (BOOL)isTotalTimerTimeValid;
- (FITFloat32)getTotalTimerTime;
- (void)setTotalTimerTime:(FITFloat32)totalTimerTime;
// TotalDistance 
- (BOOL)isTotalDistanceValid;
- (FITFloat32)getTotalDistance;
- (void)setTotalDistance:(FITFloat32)totalDistance;
// AvgSpeed 
- (BOOL)isAvgSpeedValid;
- (FITFloat32)getAvgSpeed;
- (void)setAvgSpeed:(FITFloat32)avgSpeed;
// StartTime 
- (BOOL)isStartTimeValid;
- (FITDate *)getStartTime;
- (void)setStartTime:(FITDate *)startTime;
// TotalAscent 
- (BOOL)isTotalAscentValid;
- (FITUInt16)getTotalAscent;
- (void)setTotalAscent:(FITUInt16)totalAscent;
// TotalDescent 
- (BOOL)isTotalDescentValid;
- (FITUInt16)getTotalDescent;
- (void)setTotalDescent:(FITUInt16)totalDescent;
// StartPositionLat 
- (BOOL)isStartPositionLatValid;
- (FITSInt32)getStartPositionLat;
- (void)setStartPositionLat:(FITSInt32)startPositionLat;
// StartPositionLong 
- (BOOL)isStartPositionLongValid;
- (FITSInt32)getStartPositionLong;
- (void)setStartPositionLong:(FITSInt32)startPositionLong;
// EndPositionLat 
- (BOOL)isEndPositionLatValid;
- (FITSInt32)getEndPositionLat;
- (void)setEndPositionLat:(FITSInt32)endPositionLat;
// EndPositionLong 
- (BOOL)isEndPositionLongValid;
- (FITSInt32)getEndPositionLong;
- (void)setEndPositionLong:(FITSInt32)endPositionLong;
// MaxSpeed 
- (BOOL)isMaxSpeedValid;
- (FITFloat32)getMaxSpeed;
- (void)setMaxSpeed:(FITFloat32)maxSpeed;
// AvgVertSpeed 
- (BOOL)isAvgVertSpeedValid;
- (FITFloat32)getAvgVertSpeed;
- (void)setAvgVertSpeed:(FITFloat32)avgVertSpeed;
// EndTime 
- (BOOL)isEndTimeValid;
- (FITDate *)getEndTime;
- (void)setEndTime:(FITDate *)endTime;
// TotalCalories 
- (BOOL)isTotalCaloriesValid;
- (FITUInt32)getTotalCalories;
- (void)setTotalCalories:(FITUInt32)totalCalories;
// StartElevation 
- (BOOL)isStartElevationValid;
- (FITFloat32)getStartElevation;
- (void)setStartElevation:(FITFloat32)startElevation;
// TotalMovingTime 
- (BOOL)isTotalMovingTimeValid;
- (FITFloat32)getTotalMovingTime;
- (void)setTotalMovingTime:(FITFloat32)totalMovingTime;

@end

NS_ASSUME_NONNULL_END
