/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITDate.h"
#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITTimestampCorrelationMesg : FITMessage
- (id)init;
// Timestamp 
- (BOOL)isTimestampValid;
- (FITDate *)getTimestamp;
- (void)setTimestamp:(FITDate *)timestamp;
// FractionalTimestamp 
- (BOOL)isFractionalTimestampValid;
- (FITFloat32)getFractionalTimestamp;
- (void)setFractionalTimestamp:(FITFloat32)fractionalTimestamp;
// SystemTimestamp 
- (BOOL)isSystemTimestampValid;
- (FITDate *)getSystemTimestamp;
- (void)setSystemTimestamp:(FITDate *)systemTimestamp;
// FractionalSystemTimestamp 
- (BOOL)isFractionalSystemTimestampValid;
- (FITFloat32)getFractionalSystemTimestamp;
- (void)setFractionalSystemTimestamp:(FITFloat32)fractionalSystemTimestamp;
// LocalTimestamp 
- (BOOL)isLocalTimestampValid;
- (FITLocalDateTime)getLocalTimestamp;
- (void)setLocalTimestamp:(FITLocalDateTime)localTimestamp;
// TimestampMs 
- (BOOL)isTimestampMsValid;
- (FITUInt16)getTimestampMs;
- (void)setTimestampMs:(FITUInt16)timestampMs;
// SystemTimestampMs 
- (BOOL)isSystemTimestampMsValid;
- (FITUInt16)getSystemTimestampMs;
- (void)setSystemTimestampMs:(FITUInt16)systemTimestampMs;

@end

NS_ASSUME_NONNULL_END
