/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITDate.h"
#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITWeatherAlertMesg : FITMessage
- (id)init;
// Timestamp 
- (BOOL)isTimestampValid;
- (FITDate *)getTimestamp;
- (void)setTimestamp:(FITDate *)timestamp;
// ReportId 
- (BOOL)isReportIdValid;
- (NSString *)getReportId;
- (void)setReportId:(NSString *)reportId;
// IssueTime 
- (BOOL)isIssueTimeValid;
- (FITDate *)getIssueTime;
- (void)setIssueTime:(FITDate *)issueTime;
// ExpireTime 
- (BOOL)isExpireTimeValid;
- (FITDate *)getExpireTime;
- (void)setExpireTime:(FITDate *)expireTime;
// Severity 
- (BOOL)isSeverityValid;
- (FITWeatherSeverity)getSeverity;
- (void)setSeverity:(FITWeatherSeverity)severity;
// Type 
- (BOOL)isTypeValid;
- (FITWeatherSevereType)getType;
- (void)setType:(FITWeatherSevereType)type;

@end

NS_ASSUME_NONNULL_END
