/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2024 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.158.0Release
// Tag = production/release/21.158.0-0-gc9428aa
/////////////////////////////////////////////////////////////////////////////////////////////


#import <Foundation/Foundation.h>

#import "FITDate.h"
#import "FITMessage.h"
#import "FITTypes.h"

NS_ASSUME_NONNULL_BEGIN

@interface FITWeightScaleMesg : FITMessage
- (id)init;
// Timestamp 
- (BOOL)isTimestampValid;
- (FITDate *)getTimestamp;
- (void)setTimestamp:(FITDate *)timestamp;
// Weight 
- (BOOL)isWeightValid;
- (FITFloat32)getWeight;
- (void)setWeight:(FITFloat32)weight;
// PercentFat 
- (BOOL)isPercentFatValid;
- (FITFloat32)getPercentFat;
- (void)setPercentFat:(FITFloat32)percentFat;
// PercentHydration 
- (BOOL)isPercentHydrationValid;
- (FITFloat32)getPercentHydration;
- (void)setPercentHydration:(FITFloat32)percentHydration;
// VisceralFatMass 
- (BOOL)isVisceralFatMassValid;
- (FITFloat32)getVisceralFatMass;
- (void)setVisceralFatMass:(FITFloat32)visceralFatMass;
// BoneMass 
- (BOOL)isBoneMassValid;
- (FITFloat32)getBoneMass;
- (void)setBoneMass:(FITFloat32)boneMass;
// MuscleMass 
- (BOOL)isMuscleMassValid;
- (FITFloat32)getMuscleMass;
- (void)setMuscleMass:(FITFloat32)muscleMass;
// BasalMet 
- (BOOL)isBasalMetValid;
- (FITFloat32)getBasalMet;
- (void)setBasalMet:(FITFloat32)basalMet;
// PhysiqueRating 
- (BOOL)isPhysiqueRatingValid;
- (FITUInt8)getPhysiqueRating;
- (void)setPhysiqueRating:(FITUInt8)physiqueRating;
// ActiveMet 
- (BOOL)isActiveMetValid;
- (FITFloat32)getActiveMet;
- (void)setActiveMet:(FITFloat32)activeMet;
// MetabolicAge 
- (BOOL)isMetabolicAgeValid;
- (FITUInt8)getMetabolicAge;
- (void)setMetabolicAge:(FITUInt8)metabolicAge;
// VisceralFatRating 
- (BOOL)isVisceralFatRatingValid;
- (FITUInt8)getVisceralFatRating;
- (void)setVisceralFatRating:(FITUInt8)visceralFatRating;
// UserProfileIndex 
- (BOOL)isUserProfileIndexValid;
- (FITMessageIndex)getUserProfileIndex;
- (void)setUserProfileIndex:(FITMessageIndex)userProfileIndex;
// Bmi 
- (BOOL)isBmiValid;
- (FITFloat32)getBmi;
- (void)setBmi:(FITFloat32)bmi;

@end

NS_ASSUME_NONNULL_END
